name: Java CI with Maven Wrapper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw compile war:war
    - name: Copy target to staging
      run: mkdir staging && cp ./target/*.jar staging
    - name: Upload target
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging