name: Java CI with Maven Wrapper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: ./mvnw --batch-mode --update-snapshots compile war:war
    - name: Copy target to build
      run: mkdir build && cp ./target/*.war build
    - name: Commit build
      run: |
        git config --global user.name 'CI/CD script'
        git config --global user.email 'dlucredio@users.noreply.github.com'
        git add build
        git commit -am "Automated build"
        git push